nginx:
  image: nginx:latest
  ingressPath: /
  replicaCount: 1
  
database:
  image: postgres:16
  replicaCount: 1
  host: database
  port: 5432

frontend:
  image: evershop/evershop:1.2.1
  replicaCount: 2
  serviceName: frontend-service
  containerPort: 3000
  ingressPath: / 

admin:
  image: evershop/evershop:1.2.1
  replicaCount: 1
  serviceName: admin-service
  containerPort: 3000
  ingressPath: /admin

resources: {}

persistence:
  postgresData:
    size: 8Gi
