apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: name
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data 
          persistentVolumeClaim:
            claimName: postgres-data  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}