apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
spec:
  selector:
    app: evershop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.serviceName }}
spec:
  selector:
    app: evershop-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.admin.containerPort }}
